package grammarpackage;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import static java.lang.Thread.sleep;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import sun.audio.AudioData;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;
import sun.audio.ContinuousAudioDataStream;

/**
 *
 * @author team_amazing
 */
public class GameFrame extends javax.swing.JFrame {

    // APPLICATION GLOBAL VARIABLES
    BufferedImage initDomeBuff;
    BufferedImage domeBuff;
    ImageIcon domeIcon;
    
    public GameFrame() {
        initComponents();
        
        // ===================
        // Initialization Code
        // ===================
        
        // Create resizeable DOME.png label
        initDomeBuff = null;
        try {
            initDomeBuff = ImageIO.read(new File("DOME.png"));
        } catch (Exception e) {
            e.printStackTrace();
        }
        domeBuff = (BufferedImage) initDomeBuff.getScaledInstance(lblBattleDome.getWidth(), lblBattleDome.getHeight(), Image.SCALE_SMOOTH);
        domeIcon = new ImageIcon(domeBuff);
        lblBattleDome.setIcon(domeIcon);
    }
 //Playing starting music
        //When built it shows errors but the code works, do not remove it.
        //I lied remove it because this is one big error.
//        Thread sound;
//        sound = new Thread() {
//            public void run() {
//
//                AudioPlayer MGP = AudioPlayer.player;
//                AudioStream BGM;
//                AudioData MD;
//                ContinuousAudioDataStream loop = null;
//                for (;;) {
//                    try {
//                        BGM = new AudioStream((getClass().getResourceAsStream("/resources/GameTheme.wav")));//enter the sound directory and name here
//                        AudioPlayer.player.start(BGM);
//                        sleep(35000);
//                    } catch (Exception e) {
//                        e.printStackTrace();
//                    }
//                }
//            }
//        };
//        sound.start();
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBattleDome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBattleDome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBattleDome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/DOME.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBattleDome)
                .addGap(0, 176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBattleDome)
                .addGap(0, 165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBattleDome;
    // End of variables declaration//GEN-END:variables
}
